./annsa.py:3:1: F401 'numpy.genfromtxt' imported but unused ./annsa.py:5:1: F401 'scipy.signal' imported but unused ./annsa.py:9:1: F401 'tensorflow as tf' imported but unused ./annsa.py:10:1: F401 'tensorflow.contrib.eager as tfe' imported but unused ./annsa.py:148:1: F811 redefinition of unused 'RepresentsInt' from line 56